/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;


import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.awt.Color;

public class App {
    public static void main(String[] args) {
        // TODO: Add error catching for incorrect argument length

        // TODO: Create input and output files
        // TODO: define transform

        // TODO: Catch input file DNE and output file already exists

        // TODO: Instantiate Bitmap class and use either switch cases or conditionals to perform the desired transform

        // TODO: Save the output file (with error catching) and then println that the transformation is complete
    }

    public class Bitmap {
        private final BufferedImage bitmap;

        public Bitmap(Path filePath) {
            // TODO: Implement constructor to read bitmap from file
        }

        public void flipHorizontally() {
            // TODO: Implement flip horizontally transform
        }

        public void toGrayscale() {
            // TODO: Implement grayscale transform
        }

        public void invertColors() {
            // TODO: Implement invert colors transform
        }
        public void save(Path filePath) throws IOException {
            // TODO: Implement save method to write bitmap to file
        }
    }
}
