/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.awt.Color;

public class App {
    public static void main(String[] args) throw{

        if (args.length != 3){
            throw new IllegalArgumentException("Usage: ./gradlew run --args \"input-file.bmp output-file.bmp transform\"");
        }

        Path inputPath = Paths.get(args[0]);
        Path outputPath = Paths.get(args[1]);
        String transform = args[2];

        // TODO: Catch input file DNE and output file already exists

        Bitmap bitmap = new Bitmap(inputPath);
        switch (transform){
            case "f":
                bitmap.flipHorizontally();
                break;
            case "g":
                bitmap.toGrayscale();
                break;
            case "i":
                bitmap.invertColors();
                break;
            default:
                throw new IllegalArgumentException("Unsupported transform. Available transforms:\n\"f\" to flip the image horizontally\n\"g\" to convert the image to grayscale\n\"i\" to invert the colors of hte image\n");
        }

        bitmap.save(outputPath);
        System.out.println("Transform success! Output saved to" + outputPath.toAbsolutePath());
    }

    public class Bitmap {
        private final BufferedImage bitmap;
        // These are not final because there may be a transformation in the future to alter them (such as resizing)
        private int width;
        private int height;

        public Bitmap(Path filePath) throws IOException {
            try{
                this.bitmap = ImageIO.read(filePath.toFile());
                this.width = bitmap.getWidth();
                this.height = bitmap.getHeight();
            } catch (IOException ioe){
                ioe.printStackTrace();
            }
        }

        public void flipHorizontally() {
            // TODO: Implement flip horizontally transform
        }

        public void toGrayscale() {
            // Iterate over each pixel and calculate their average value, then update that pixel's color
            for (int row = 0; row < this.height; row++){
                for(int column = 0; column < this.width; column++){
                    int pixel = bitmap.getRGB(column, row);
                    Color color = new Color(pixel);

                    int red = color.getRed();
                    int green = color.getGreen();
                    int blue = color.getBlue();
                    int avg = (red + green + blue)/3;

                    Color newColor = new Color(avg, avg, avg);
                    bitmap.setRGB(column, row, newColor.getRGB());
                }
            }
        }

        public void invertColors() {
            // TODO: Implement invert colors transform
        }
        public void save(Path filePath) throws IOException {
            // TODO: Implement save method to write bitmap to file
        }
    }
}
